In [20]:
import numpy as np
import pandas as pd
#Pandas数据结构Dataframe：基本概念及创建

In [21]:
# Dataframe带有index（行标签）和columns（列标签）
data={'name':['jack','tom','mary'],
      'age':[18,19,20],
      'gender':['m','m','w']}
frame=pd.DataFrame(data)
print(frame)
print(frame.index,'\n该数据类型为',type(frame.index))
print(frame.columns,'\n该数据类型为',type(frame.columns))
print(frame.values,'\n该数据类型为',type(frame.values))
# .index查看行标签
# .columns查看列标签
# .values查看值，数据类型为ndarray

   name  age gender
0  jack   18      m
1   tom   19      m
2  mary   20      w
RangeIndex(start=0, stop=3, step=1) 
该数据类型为 <class 'pandas.core.indexes.range.RangeIndex'>
Index(['name', 'age', 'gender'], dtype='object') 
该数据类型为 <class 'pandas.core.indexes.base.Index'>
[['jack' 18 'm']
 ['tom' 19 'm']
 ['mary' 20 'w']] 
该数据类型为 <class 'numpy.ndarray'>


In [22]:
data1={'a':[1,2,3],
       'b':[3,4,5],
       'c':[5,6,7]}
data2={'one':np.random.rand(3),
       'two':np.random.rand(3)}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)
print(df1)
print(df2)
#字典的值的长度必须保持一致！
df3=pd.DataFrame(data1,columns=['b','c','a','d'])
f1 = pd.DataFrame(data1, columns = ['b','c'])
print(f1)
# columns参数：可以重新指定列的顺序，格式为list，
# 如果现有数据中没有该列（比如'd'），则产生NaN值
# 如果columns重新指定时候，列的数量可以少于原数据
df2 = pd.DataFrame(data2, index = ['f1','f2','f3'])
df2
#index参数：重新定义index，格式为list，长度必须保持一致

   a  b  c
0  1  3  5
1  2  4  6
2  3  5  7
        one       two
0  0.447183  0.991121
1  0.258174  0.851581
2  0.668591  0.514401
   b  c
0  3  5
1  4  6
2  5  7


one       two
f1  0.447183  0.991121
f2  0.258174  0.851581
f3  0.668591  0.514401

In [23]:
data1 = {'one':pd.Series(np.random.rand(2)),
        'two':pd.Series(np.random.rand(3))}  # 没有设置index的Series
data2 = {'one':pd.Series(np.random.rand(2), index = ['a','b']),
        'two':pd.Series(np.random.rand(3),index = ['a','b','c'])}  # 设置了index的Series
print(data1)
print(data2)
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
print(df1)
print(df2)
# 由Seris组成的字典 创建Dataframe，columns为字典key，index为Series的标签（如果Series没有指定标签，则是默认数字标签）
# Series可以长度不一样，生成的Dataframe会出现NaN值

{'one': 0    0.817278
1    0.570800
dtype: float64, 'two': 0    0.582916
1    0.252218
2    0.120373
dtype: float64}
{'one': a    0.894384
b    0.798191
dtype: float64, 'two': a    0.019060
b    0.554981
c    0.997922
dtype: float64}
        one       two
0  0.817278  0.582916
1  0.570800  0.252218
2       NaN  0.120373
        one       two
a  0.894384  0.019060
b  0.798191  0.554981
c       NaN  0.997922


In [24]:
ar = np.random.rand(9).reshape(3,3)
print(ar)
df1 = pd.DataFrame(ar)
df2 = pd.DataFrame(ar, index = ['a', 'b', 'c'], columns = ['one','two','three'])  # 可以尝试一下index或columns长度不等于已有数组的情况
print(df1)
print(df2)
# 通过二维数组直接创建Dataframe，得到一样形状的结果数据，如果不指定index和columns，两者均返回默认数字格式
# index和colunms指定长度与原数组保持一致

[[0.43971274 0.1013706  0.92117219]
 [0.24943464 0.20535697 0.81866245]
 [0.04419047 0.65632097 0.09812954]]
          0         1         2
0  0.439713  0.101371  0.921172
1  0.249435  0.205357  0.818662
2  0.044190  0.656321  0.098130
        one       two     three
a  0.439713  0.101371  0.921172
b  0.249435  0.205357  0.818662
c  0.044190  0.656321  0.098130


In [25]:
data = [{'one': 1, 'two': 2}, {'one': 5, 'two': 10, 'three': 20}]
print(data)
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data, index = ['a','b'])
df3 = pd.DataFrame(data, columns = ['one','two'])
print(df1)
print(df2)
print(df3)
# 由字典组成的列表创建Dataframe，columns为字典的key，index不做指定则为默认数组标签
# colunms和index参数分别重新指定相应列及行标签

[{'one': 1, 'two': 2}, {'one': 5, 'two': 10, 'three': 20}]
   one  two  three
0    1    2    NaN
1    5   10   20.0
   one  two  three
a    1    2    NaN
b    5   10   20.0
   one  two
0    1    2
1    5   10


In [26]:
data = {'Jack':{'math':90,'english':89,'art':78},
       'Marry':{'math':82,'english':95,'art':92},
       'Tom':{'math':78,'english':67}}
df1 = pd.DataFrame(data)
print(df1)
# 由字典组成的字典创建Dataframe，columns为字典的key，
# index为子字典的key
df2 = pd.DataFrame(data, columns = ['Jack','Tom','Bob'])
df3 = pd.DataFrame(data, index = ['a','b','c'])
print(df2)
print(df3)
# columns参数可以增加和减少现有列，如出现新的列，值为NaN
# index在这里和之前不同，并不能改变原有index，
# 如果指向新的标签，值为NaN （非常重要！）

         Jack  Marry   Tom
math       90     82  78.0
english    89     95  67.0
art        78     92   NaN
         Jack   Tom  Bob
math       90  78.0  NaN
english    89  67.0  NaN
art        78   NaN  NaN
   Jack  Marry  Tom
a   NaN    NaN  NaN
b   NaN    NaN  NaN
c   NaN    NaN  NaN


In [28]:
# 一般用于选择列，也可以选择行

df = pd.DataFrame(np.random.rand(12).reshape(3,4)*100,
                   index = ['one','two','three'],
                   columns = ['a','b','c','d'])
print(df)
print('-----')

data1 = df['a']
data2 = df[['b','c']]  # 尝试输入 data2 = df[['b','c','e']]
print(data1)
print(data2)
# df[]默认选择列，[]中写列名（所以一般数据colunms都会单独制定，不会用默认数字列名，以免和index冲突）
# 单选列为Series，print结果为Series格式
# 多选列为Dataframe，print结果为Dataframe格式

data3 = df[:1]
#data3 = df[0]
#data3 = df['one']
print(data3,type(data3))
# df[]中为数字时，默认选择行，且只能进行切片的选择，
# 不能单独选择（df[0]）
# 输出结果为Dataframe，即便只选择一行
# df[]不能通过索引标签名来选择行(df['one'])
# 核心笔记：df[col]一般用于选择列，[]中写列名

               a          b          c          d
one    29.006000  68.810954  84.236701  94.216056
two    82.318654  38.452386  77.461915  76.532948
three  48.286669  12.358623  36.615204  63.450591
-----
one      29.006000
two      82.318654
three    48.286669
Name: a, dtype: float64
               b          c
one    68.810954  84.236701
two    38.452386  77.461915
three  12.358623  36.615204


KeyError: 'one'

In [ ]:
# 多个标签索引，如果标签不存在，则返回NaN
# 顺序可变
# 核心笔记：df.loc[label]主要针对index选择行，
# 同时支持指定index，及默认数字index

In [ ]:
# 类似list的索引，其顺序就是dataframe的整数位置，从0开始计
# 单位置索引
# 和loc索引不同，不能索引超出数据行数的整数位置
# 多位置索引
# 顺序可变
# 切片索引
# 末端不包含

In [ ]:
# 先选择列再选择行 —— 相当于对于一个数据，先筛选字段，再选择数据量

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
print(df)
print('------')

print(df['a'].loc[['one','three']])   # 选择a列的one，three行
print(df[['b','c','d']].iloc[::2])   # 选择b，c，d列的one，three行
print(df[df['a'] < 50].iloc[:2])   # 选择满足判断索引的前两行数据