In [1]:
import numpy as np

In [2]:
a=np.random.random((5,5))
max,min=a.max(),a.min()
a=(a-min)/(max-min)
a

array([[0.21486065, 0.91069001, 0.44277693, 0.06116579, 0.        ],
       [0.35747169, 0.51149757, 0.5858342 , 0.46176369, 0.0882112 ],
       [1.        , 0.83494554, 0.56584295, 0.48308873, 0.71077015],
       [0.63813735, 0.66650789, 0.09242064, 0.53104544, 0.09456441],
       [0.12467042, 0.45620681, 0.86283399, 0.74549853, 0.49741524]])

In [3]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

<ipython-input-3-70844dc2a6fc>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [5]:
a=np.random.random((5,3))
b=np.random.random((3,2))
np.dot(a,b)

array([[0.33159842, 0.20023101],
       [1.06340359, 0.69957227],
       [1.03790484, 0.79276876],
       [0.72397945, 0.58543876],
       [0.67097402, 0.50372589]])

In [9]:
a=np.arange(10)
a[4:9]*=-1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9])

In [10]:
print(sum(range(5),-1))

9


In [15]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))
#np.ceil(a)ceiling向上取整np.floor(a)向下取整
#np.copysign(a, b) : 将b中各元素的符号赋值给数组a的对应元素
Z

[ 8.  1.  4.  8. -6. -3.  4. -9. -2.  1.]


array([ 7.70118334,  0.79674982,  3.34375171,  7.88285712, -5.33011219,
       -2.37641377,  3.68193866, -8.38417005, -1.96925943,  0.70431416])

In [16]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 8]


In [17]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2020-10-04
Today is 2020-10-05
Tomorrow is 2020-10-06


In [18]:
np.arange('2020-10', '2020-11', dtype='datetime64[D]')

array(['2020-10-01', '2020-10-02', '2020-10-03', '2020-10-04',
       '2020-10-05', '2020-10-06', '2020-10-07', '2020-10-08',
       '2020-10-09', '2020-10-10', '2020-10-11', '2020-10-12',
       '2020-10-13', '2020-10-14', '2020-10-15', '2020-10-16',
       '2020-10-17', '2020-10-18', '2020-10-19', '2020-10-20',
       '2020-10-21', '2020-10-22', '2020-10-23', '2020-10-24',
       '2020-10-25', '2020-10-26', '2020-10-27', '2020-10-28',
       '2020-10-29', '2020-10-30', '2020-10-31'], dtype='datetime64[D]')

In [24]:
a=np.ones(3)*1
b=np.ones(3)*2
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)

array([-1.5, -1.5, -1.5])

In [26]:
a=np.zeros((5,5))
a+=np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [27]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
#np.fromiter()（iterable，dtype，count = -1）
#iterable：可迭代对象为数组提供数据。
     # dtype：返回数组的数据类型。
     # count：int，可选
     #     要从* iterable *中读取的项目数。 默认值为-1，
     #     这意味着所有数据都被读取。
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [29]:
z = np.linspace(0,1,11,endpoint=False)[1:]
#start, stop, num=50
z

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091])

In [32]:
a=np.random.random(10)
a
a.sort()

array([0.07005523, 0.27374164, 0.34513962, 0.45266295, 0.54952862,
       0.57922061, 0.65214809, 0.69256448, 0.83738733, 0.91622623])

In [33]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [34]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A,B)
equal

False