In [3]:
import numpy as   np

In [4]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.79030598 0.58365478 0.74201775 0.80056863 0.30866791 0.69067683
 1.04564821 0.92988721 0.52699603 0.93071249]
[0.72865231 0.28064709 0.2479056  0.1803404  0.3687534  0.02493046
 0.52191624 0.56575021 0.23091291 1.39779692]


In [6]:
a=np.random.random(10)
a[a.argmax()]=1
#a.argmax返回沿轴axis最大值的索引axis=0代表列，axis=1代表行
a

array([1.        , 0.15824004, 0.65209082, 0.63409719, 0.475457  ,
       0.02999353, 0.52921741, 0.11439561, 0.03750464, 0.28285272])

In [7]:
Z = np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
Z
#二维坐标系中,X轴可以取三个值1,2,3, Y轴可以取三个值7,8, 请问可以获得多少个点的坐标?
# 显而易见是6个:
# (1,7)(2,7)(3,7)
# (1,8)(2,8)(3,8)
#
# np.meshgrid()就是干这个的!

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [8]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
#np.subtract.outer(b,a)是b[:,None]-a的函数对应
# 其含义是：有两个向量a、b，
# 要实现a中的每个元素与b中的每个元素进行比较
print(np.linalg.det(C))
# #np.linalg.det():矩阵求行列式
#
# 二、np.linalg.inv()：矩阵求逆
#
# 三、np.linalg.norm():求范数

3638.1636371179666


In [11]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-11-d1aae3368800>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


In [16]:
a=np.random.random((10,2))
x,y=np.atleast_2d(a[:,0],a[:,1])
d=np.sqrt((x-x.T)**2+(y-y.T)**2)
d
# # 方法2
# # Much faster with scipy
# import scipy
# # Thanks Gavin Heverly-Coulson (#issue 1)
# import scipy.spatial
# D = scipy.spatial.distance.cdist(Z,Z)
# print (D)

array([[0.62693816, 0.90973141, 0.90275362, 0.94308009, 0.78929454,
        0.55128911, 0.99453278, 0.02796779, 0.22400287, 0.5034266 ]])

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

In [ ]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

In [21]:
Z = np.random.randint(0,10,(3,3))
print (Z)
Z1=Z[:,1]
print (Z1)
Z2=Z1.argsort()
print(Z2)
Z3=Z[Z2]
print(Z3)

[[3 9 4]
 [4 6 2]
 [0 2 4]]
[9 6 2]
[2 1 0]
[[0 2 4]
 [4 6 2]
 [3 9 4]]


In [22]:
Z = np.random.randint(0,3,(3,10))
~Z.any(axis=0).any()




False