In [1]:
import numpy as np

In [3]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

float64


In [4]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it:
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [5]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [8]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
#np.add.at()是将传入的数组中制定下标位置的元素加上指定的值
# I的下标对应的Z值加1
print(Z)
print(I)

[3. 2. 3. 5. 2. 2. 2. 2. 5. 4.]
[3 9 6 9 3 8 0 3 8 7 2 8 4 5 3 2 9 1 8 0]


In [9]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [12]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first.
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)
print (I)
print(F)

8
[[[0 1 1]
  [0 1 1]
  [0 0 1]
  [0 1 1]
  [0 0 1]
  [0 1 0]
  [0 0 1]
  [1 1 1]
  [1 0 1]
  [1 1 0]
  [1 0 0]
  [0 1 1]
  [0 0 0]
  [1 0 1]
  [0 0 1]
  [1 0 0]]

 [[0 1 1]
  [0 0 1]
  [0 1 0]
  [0 1 1]
  [1 0 0]
  [1 1 0]
  [0 1 1]
  [1 0 0]
  [0 1 0]
  [1 1 1]
  [0 0 0]
  [1 1 0]
  [1 1 0]
  [1 1 1]
  [1 1 0]
  [0 1 0]]

 [[0 0 0]
  [0 0 0]
  [0 1 0]
  [0 0 1]
  [0 0 0]
  [0 0 0]
  [1 0 0]
  [1 1 1]
  [0 0 1]
  [1 1 0]
  [0 1 0]
  [1 1 0]
  [0 1 1]
  [1 1 0]
  [0 1 0]
  [1 0 1]]

 [[0 0 0]
  [1 0 1]
  [0 0 1]
  [1 1 1]
  [0 1 0]
  [0 1 1]
  [1 0 0]
  [0 1 1]
  [1 1 1]
  [1 0 1]
  [1 0 0]
  [1 0 0]
  [0 1 0]
  [1 1 1]
  [1 0 0]
  [1 1 0]]

 [[1 0 1]
  [0 0 0]
  [0 0 1]
  [0 0 0]
  [0 1 0]
  [0 0 0]
  [0 1 1]
  [0 1 0]
  [0 1 1]
  [0 0 1]
  [0 1 1]
  [1 0 0]
  [0 1 1]
  [1 1 1]
  [1 0 0]
  [0 0 1]]

 [[0 1 1]
  [1 1 1]
  [0 1 1]
  [1 1 0]
  [1 1 0]
  [1 1 1]
  [1 1 0]
  [0 1 0]
  [1 1 1]
  [0 1 1]
  [0 1 0]
  [1 1 0]
  [0 0 1]
  [0 0 0]
  [1 1 1]
  [0 1 0]]

 [[0 0 0]
  [0 0 1]
  [0 0

In [17]:
a=np.arange(16).reshape((2,2,2,2))
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)

In [18]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

NameError: name 'D' is not defined

In [19]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.einsum("ij,ji->i", A, B)
# np.sum(A * B.T, axis=1)

array([2.33140831, 1.16208855, 0.3010052 , 1.42198903, 1.34036733])

In [20]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [22]:
a=np.ones((5,5,3))
b=np.ones((5,5))
c=a*b[:,:,None]

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

In [23]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 0, 11) ( 0, 30) ( 1, 31) ( 1, 70) ( 1, 77) ( 1, 87) (11, 30) (16, 48)
 (22, 38) (22, 67) (24, 48) (24, 98) (26, 43) (26, 54) (28, 28) (28, 41)
 (31, 87) (35, 63) (35, 76) (38, 67) (43, 53) (43, 54) (43, 56) (48, 48)
 (48, 98) (53, 56) (63, 76) (70, 77)]


In [24]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


In [25]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
#https://blog.csdn.net/qq_36165570/article/details/99594949
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [26]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [27]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    #sum应该是默认的axis=0 就是普通的相加
    #axis=1以后就是将一个矩阵的每一行向量相加
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[ 1.24087887  2.47164964  6.0804209   2.29972358  2.7636479   4.75271807
  0.2526462   7.612313   12.89770375  8.26838845]


In [ ]:
# # based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

In [28]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[5 8 8 2 6 3 6 8 4 2]
 [7 0 7 1 8 7 5 8 9 9]
 [8 0 6 8 8 0 3 1 1 8]
 [7 9 0 6 1 7 0 9 1 5]
 [2 8 5 2 1 0 5 0 2 7]
 [2 2 0 1 3 2 0 8 3 2]
 [3 0 4 6 1 3 1 1 6 9]
 [6 4 6 1 4 0 5 7 7 4]
 [2 9 2 1 7 0 1 6 5 2]
 [7 8 3 8 3 8 4 6 6 1]]
[[0 0 0 0 0]
 [0 5 8 8 2]
 [0 7 0 7 1]
 [0 8 0 6 8]
 [0 7 9 0 6]]


<ipython-input-28-f291d59e661b>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [7]:
Z = np.arange(1,15)
from numpy.lib import stride_tricks
R=stride_tricks.as_strided(Z,shape=(11,4),strides=(4,4))
# shape 为变形后的形状；
# strides中各个数字为每一“步”的字节数，
# 每一组内的间隔是1(数据类型int32为4字节)，
# 组与组件的间隔也是1(4字节)，故而strides为(4,4)
print (R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
