In [14]:
import numpy as np

In [15]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
# 返回值：
# 总共有三个返回值u,s,v
# u大小为(M,M)，s大小为(M,N)，v大小为(N,N)。
# A = u*s*v
# 其中s是对矩阵a的奇异值分解。
# s除了对角元素不为0，其他元素都为0，并且对角元素从大到小排列。
# s中有n个奇异值，一般排在后面的比较接近0，
# 所以仅保留比较大的r个奇异值。# Singular Value Decomposition
rank = np.sum(S >0)
print (rank)

10


In [16]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z))
print(np.bincount(Z).argmax())

[0 1 7 6 4 1 9 8 8 3 8 2 7 8 3 0 9 6 1 6 4 6 3 9 5 0 3 7 9 7 9 0 4 2 2 8 4
 2 6 0 4 4 4 8 9 0 0 8 1 4]
[7 4 4 4 8 1 5 4 7 6]
4


In [17]:
Z = np.random.randint(0,5,(10,10))
from  numpy.lib import stride_tricks
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[3 2 4]
   [1 0 3]
   [4 3 3]]

  [[2 4 3]
   [0 3 0]
   [3 3 1]]

  [[4 3 3]
   [3 0 3]
   [3 1 2]]

  [[3 3 4]
   [0 3 0]
   [1 2 0]]

  [[3 4 4]
   [3 0 0]
   [2 0 4]]

  [[4 4 2]
   [0 0 3]
   [0 4 4]]

  [[4 2 0]
   [0 3 0]
   [4 4 4]]

  [[2 0 0]
   [3 0 0]
   [4 4 3]]]


 [[[1 0 3]
   [4 3 3]
   [2 3 1]]

  [[0 3 0]
   [3 3 1]
   [3 1 4]]

  [[3 0 3]
   [3 1 2]
   [1 4 3]]

  [[0 3 0]
   [1 2 0]
   [4 3 4]]

  [[3 0 0]
   [2 0 4]
   [3 4 1]]

  [[0 0 3]
   [0 4 4]
   [4 1 1]]

  [[0 3 0]
   [4 4 4]
   [1 1 4]]

  [[3 0 0]
   [4 4 3]
   [1 4 2]]]


 [[[4 3 3]
   [2 3 1]
   [2 1 1]]

  [[3 3 1]
   [3 1 4]
   [1 1 3]]

  [[3 1 2]
   [1 4 3]
   [1 3 0]]

  [[1 2 0]
   [4 3 4]
   [3 0 1]]

  [[2 0 4]
   [3 4 1]
   [0 1 0]]

  [[0 4 4]
   [4 1 1]
   [1 0 4]]

  [[4 4 4]
   [1 1 4]
   [0 4 2]]

  [[4 4 3]
   [1 4 2]
   [4 2 0]]]


 [[[2 3 1]
   [2 1 1]
   [1 4 4]]

  [[3 1 4]
   [1 1 3]
   [4 4 2]]

  [[1 4 3]
   [1 3 0]
   [4 2 1]]

  [[4 3 4]
   [3 0 1]
   [2 1 4]]

  [[3 4 1]
   

In [18]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 8  8 11  9  3]
 [ 8  6 11 18 14]
 [11 11  6 42  8]
 [ 9 18 42  2  3]
 [ 3 14  8  3  1]]


In [19]:
#如何直接计算p个矩阵的乘积(n,1)
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)
#It works, because:
#M is (p,n,n)
#V is (p,n,1)
#Thus, summing over the paired axes 0 and 0 (of M and V independently),
#and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [20]:
#如何得到一个区域(block-sum)的和(区域大小为4x4)?
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [21]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [23]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
Z[np.argpartition(-Z,n)[:n]]
# numpy.argpartition(a, kth, axis=-1, kind='introselect', order=None)
# 需要知道该函数返回的是重组后数据的索引数组
# 本文介绍该函数前三个参数，及该函数具体用法。
#a:要排序的矩阵，默认升序排列；该参数为-a时，降序排列
#kth:  int或int序列。该参数为数组的索引值。具体用法下边举例介绍
# axis:int或none，可选。要排序的轴。默认值是-1，它沿着最后一个轴。

array([9998, 9999, 9997, 9995, 9996])

In [24]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [ ]:
x = np.random.rand()
# np.power(x,3)
x*x*x
# np.einsum('i,i,i->i',x,x,x)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print (Z)
Z[Z.max(axis=1) != Z.min(axis=1),:]
print (U)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

In [ ]:
#inner, outer, sum, mul函数
# A = np.random.uniform(0,1,10)
# B = np.random.uniform(0,1,10)
# print ('sum')
# print (np.einsum('i->', A))# np.sum(A)
# print ('A * B')
# print (np.einsum('i,i->i', A, B)) # A * B
# print ('inner')
# print (np.einsum('i,i', A, B))    # np.inner(A, B)
# print ('outer')
# print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

In [27]:
#如何用等距样例(equidistant samples)
#对其进行采样(sample)?
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)